### ISSUE TITLE
Uncaught Error: Expected a valid key to convert, with length 1, 2, 4, 8, 32, 33

### ISSUE THREAD

**Issue by ltfschoen** [Phala-Network/website-nextjs#78]
When I go to https://app.phala.network/khala and try to connect my Polkadot.js account using Brave browser, I get the following error as mentioned here https://grillapp.net/@luke/polkadot-d-app-errors-when-handling-accounts-supplied-by-the-47114, where the solution is mentioned here https://github.com/polkadot-js/extension/issues/1250

**Comment by Leechael** [comment]
@ltfschoen Hi, sorry for the late reply. Your report is in the wrong repo. The correct repo for the app can be found here: https://github.com/Phala-Network/apps/issues

I will forward your report to our team and close this issue since it is irrelevant.
